spring:
  application:
    name: deploy-board

  messages:
    basename: messages
    encoding: UTF-8

  web:
    resources:
      add-mappings: true

  profiles:
    include:
      - database
      - security
      - docs
      - monitoring

server:
  error:
    path: /error
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false


