spring:
  application:
    name: deploy-board
  profiles:
    active: local

  messages:
    basename: messages
    encoding: UTF-8

  web:
    resources:
      add-mappings: true

  config:
    import:
      - classpath:application-database.yaml
      - classpath:application-security.yaml
      - classpath:application-docs.yaml
      - classpath:application-monitoring.yaml

server:
  error:
    path: /error
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false


